# Generated by Django 6.1.2 on 2026-10-06 20:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_refonte_2026'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelloAssoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Reçue le')),
                ('event_type', models.CharField(blank=True, max_length=40, verbose_name='Type')),
                ('order_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Commande')),
                ('form_slug', models.CharField(blank=True, max_length=200, verbose_name='Campagne')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Contenu')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name="IP d'origine")),
                ('secret_ok', models.BooleanField(default=False, verbose_name='URL secrète utilisée')),
                ('verified', models.BooleanField(default=False, verbose_name="Confirmée via l'API HelloAsso")),
                ('status', models.CharField(choices=[('received', 'Reçue'), ('processed', 'Traitée'), ('ignored', 'Ignorée'), ('rejected', 'Rejetée'), ('error', 'Erreur')], default='received', max_length=12, verbose_name='Statut')),
                ('result', models.TextField(blank=True, verbose_name='Résultat')),
            ],
            options={
                'verbose_name': 'Notification HelloAsso',
                'verbose_name_plural': 'Notifications HelloAsso',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex. « 2026-2027 ». Affiché sur tout le site.', max_length=20, unique=True, verbose_name='Saison')),
                ('start_date', models.DateField(verbose_name='Début de la saison')),
                ('end_date', models.DateField(verbose_name='Fin de la saison')),
                ('is_current', models.BooleanField(default=False, help_text="Une seule saison peut être « en cours » : c'est elle qui détermine qui est adhérent·e à jour.", verbose_name='Saison en cours')),
                ('registrations_open', models.BooleanField(default=True, verbose_name='Adhésions ouvertes')),
                ('helloasso_url', models.URLField(blank=True, help_text="Copier-coller le lien public de la campagne d'adhésion HelloAsso.", max_length=500, verbose_name='Lien de la campagne HelloAsso')),
                ('helloasso_org_slug', models.CharField(blank=True, editable=False, max_length=120, verbose_name='Organisation HelloAsso')),
                ('helloasso_form_type', models.CharField(blank=True, editable=False, max_length=30, verbose_name='Type de formulaire')),
                ('helloasso_form_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=200, verbose_name='Identifiant de la campagne')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Montant de la cotisation (€)')),
                ('pitch', models.TextField(blank=True, help_text="Texte affiché sur la page d'adhésion pour cette saison.", verbose_name='Pourquoi adhérer ? (Markdown)')),
                ('helloasso_title', models.CharField(blank=True, editable=False, max_length=200, verbose_name='Titre sur HelloAsso')),
                ('helloasso_start', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Début de validité (HelloAsso)')),
                ('helloasso_end', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fin de validité (HelloAsso)')),
                ('helloasso_state', models.CharField(blank=True, editable=False, max_length=30, verbose_name='État sur HelloAsso')),
                ('last_synced_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Dernière synchronisation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
            ],
            options={
                'verbose_name': 'Saison',
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='unique_current_season'), models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='season_dates_order')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Valide'), ('refunded', 'Remboursée'), ('cancelled', 'Annulée')], default='active', max_length=12, verbose_name='Statut')),
                ('source', models.CharField(choices=[('helloasso', 'HelloAsso'), ('manual', 'Saisie manuelle'), ('legacy', "Reprise de l'ancien site")], default='manual', max_length=12, verbose_name='Origine')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cotisation (€)')),
                ('donation', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Don associé (€)')),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Carte bancaire (HelloAsso)'), ('cash', 'Espèces'), ('check', 'Chèque'), ('transfer', 'Virement'), ('free', 'Gratuit / offert'), ('other', 'Autre')], max_length=12, verbose_name='Moyen de paiement')),
                ('tier_label', models.CharField(blank=True, max_length=200, verbose_name='Formule')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'adhésion")),
                ('helloasso_order_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Commande HelloAsso')),
                ('helloasso_item_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Ligne HelloAsso')),
                ('membership_card_url', models.URLField(blank=True, max_length=500, verbose_name="Carte d'adhérent·e HelloAsso")),
                ('payer_name', models.CharField(blank=True, max_length=200, verbose_name='Payeur·se')),
                ('payer_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail du payeur·se')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enregistrée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Saisie par')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='members.person', verbose_name='Personne')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='memberships.season', verbose_name='Saison')),
            ],
            options={
                'verbose_name': 'Adhésion',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['season', 'status'], name='memberships_season__ae8fcf_idx')],
            },
        ),
    ]
