# Generated by Django 6.1.2 on 2026-10-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_seasons_and_legacy_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='helloasso_other_urls',
            field=models.TextField(blank=True, help_text="Rarement utile : si une campagne a été recréée en cours de saison, coller ici le lien de l'ancienne (un lien par ligne) pour que ses adhésions comptent aussi dans cette saison.", verbose_name='Autres campagnes HelloAsso de la saison'),
        ),
    ]
