# Generated by Django 6.1.2 on 2026-10-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_past_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='banner',
            field=models.ImageField(blank=True, help_text='Copie de la bannière de la campagne HelloAsso, mise à jour à chaque synchronisation.', upload_to='saisons/', verbose_name='Bannière'),
        ),
        migrations.AddField(
            model_name='season',
            name='helloasso_banner_url',
            field=models.URLField(blank=True, editable=False, max_length=500, verbose_name="Bannière d'origine (HelloAsso)"),
        ),
    ]
