# Generated by Django 2.2.9 on 2023-11-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='ID Opération')),
                ('desc', models.TextField(verbose_name='Description')),
                ('direction', models.CharField(choices=[('C', 'Crédit'), ('D', 'Débit'), ('R', 'Remboursement')], default='D', max_length=1, verbose_name="Type d'opération")),
                ('amout', models.FloatField(verbose_name='Montant')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('status', models.CharField(choices=[('R', 'Reçue'), ('P', 'Prévisionnelle'), ('F', 'A faire'), ('J', 'En attente justificatif'), ('V', 'En attente de validation CA'), ('D', 'Demande des identifiants'), ('C', 'Virement en cours')], default='J', max_length=1, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Opération',
            },
        ),
    ]
