# Generated by Django 2.2.9 on 2023-11-21 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='dest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination_operation', to=settings.AUTH_USER_MODEL, verbose_name="Receveur de l'opération"),
        ),
        migrations.AddField(
            model_name='operation',
            name='src',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_operation', to=settings.AUTH_USER_MODEL, verbose_name="Emetteur de l'opération"),
        ),
    ]
