# Generated by Django 6.1.2 on 2026-10-06 20:14

import core.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_initial'),
        ('dashboard', '0003_refonte_2026'),
        ('members', '0002_refonte_2026'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['date', 'pk'], 'verbose_name': 'Dépense'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_created'], 'verbose_name': 'Note de frais', 'verbose_name_plural': 'Notes de frais'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['-date', '-date_created'], 'verbose_name': 'Opération'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modifiée le'),
        ),
        migrations.AddField(
            model_name='operation',
            name='attachment',
            field=models.FileField(blank=True, storage=core.storage.private_storage, upload_to=core.storage.UploadTo('bank/operations'), verbose_name='Pièce jointe'),
        ),
        migrations.AddField(
            model_name='operation',
            name='category',
            field=models.CharField(choices=[('memberships', 'Adhésions & dons'), ('projects', 'Projets & aides'), ('equipment', 'Matériel'), ('events', 'Évènements'), ('services', 'Prestations'), ('reimbursements', 'Remboursements de frais'), ('fees', 'Frais bancaires & abonnements'), ('grants', 'Subventions'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='operation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Saisie par'),
        ),
        migrations.AddField(
            model_name='operation',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='bank.invoice', verbose_name='Note de frais remboursée'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(verbose_name='Montant (€)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Auteur·ice'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='comm',
            field=models.TextField(blank=True, null=True, verbose_name='Précisions'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Ajoutée le'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='linked_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.invoice', verbose_name='Note de frais'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='proof',
            field=models.FileField(blank=True, null=True, storage=core.storage.private_storage, upload_to=core.storage.UploadTo('img/proofs'), verbose_name='Justificatif'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Dépense'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Auteur·ice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Déposée le'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='dashboard.project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('V', 'En attente de validation par le CA'), ('F', 'Validée — remboursement à faire'), ('D', 'Informations bancaires demandées'), ('J', 'Justificatif(s) manquant(s)'), ('C', 'Virement en cours'), ('R', 'Remboursement effectué'), ('X', 'Remboursement refusé')], default='V', max_length=1, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Intitulé'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Montant total (calculé)'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='amount',
            field=models.FloatField(verbose_name='Montant (€)'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Saisie le'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='desc',
            field=models.TextField(verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name="N° d'opération"),
        ),
        migrations.AlterField(
            model_name='operation',
            name='third_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='members.person', verbose_name='Tiers'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('C', 'Crédit'), ('D', 'Débit'), ('R', 'Remboursement')], default='D', max_length=1, verbose_name='Type'),
        ),
    ]
