version: '3.8'

networks:
  magellans_site:
    driver: 'bridge'

services:
  # PostgreSQL service
  postgres:
    restart: always
    container_name: django-pgsql
    image: postgres:16-bullseye
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - magellans_site

  # Redis service
  redis:
    restart: always
    container_name: django-redis
    image: redis:5
    command: ["redis-server"]
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - magellans_site

  # Django service
  django:
    restart: always
    container_name: django-app
    build:
      context: ./app
    command: ${COMMAND}
    volumes:
      - ./app:/app
    depends_on:
      - postgres
      - redis
    networks:
      - magellans_site

  # Nginx service
  nginx:
    restart: always
    container_name: django-nginx
    image: nginx:latest
    volumes:
      - ./nginx/${NGINX_CONF_FILE}:/etc/nginx/conf.d/default.conf
      - ${STATICFILES_DIR}:/app/staticfiles/
      - ${SSL_CERTS_DIR}:/app/ssl/
    ports:
      - "80:80"
      - "443:443"
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)

    depends_on:
      - django
    networks:
      - magellans_site

  mail-server:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: django-mail
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.magellans.fr
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    volumes:
      - ./volumes/mail/data/:/var/mail/
      - ./volumes/mail/state/:/var/mail-state/
      - ./volumes/mail/logs/:/var/log/mail/
      - ./volumes/mail/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ${SSL_CERTS_DIR}:/app/ssl
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      - magellans_site

  roundcube:
    image: roundcube/roundcubemail:latest
    links:
      - postgres
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=pgsql
      - ROUNDCUBEMAIL_DB_HOST=${DB_HOST}
      - ROUNDCUBEMAIL_DB_PORT=${DB_PORT}
      - ROUNDCUBEMAIL_DB_USER=${DB_USER}
      - ROUNDCUBEMAIL_DB_PASSWORD=${DB_PASSWORD}
      - ROUNDCUBEMAIL_DB_NAME=${DB_NAME}

volumes:
  postgres_data:
  redis_data: