version: '3.8'

networks:
  magellans_site:
    driver: 'bridge'

services:
  # PostgreSQL service
  postgres:
    restart: always
    container_name: django-pgsql
    image: postgres:16-bullseye
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - magellans_site

  # Redis service
  redis:
    restart: always
    container_name: django-redis
    image: redis:5
    command: redis-server
    volumes:
      - redis_data:/data
    networks:
      - magellans_site


  # Django service
  django:
    restart: always
    container_name: django-app
    build:
      context: ./app
    command: ${COMMAND}
    volumes:
      - ./app:/app
    depends_on:
      - postgres
      - redis
    networks:
      - magellans_site


  # Nginx service
  nginx:
    restart: always
    container_name: django-nginx
    image: nginx:latest
    volumes:
      - ./nginx/${NGINX_CONF_FILE}:/etc/nginx/conf.d/default.conf
      - ./app/staticfiles/:/app/staticfiles/
      - ${SSL_CERTS_DIR}:${SSL_CERTS_DIR}
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - magellans_site


volumes:
  postgres_data:
  redis_data: