version: '3.8'

networks:
  magellans_site:
    driver: 'bridge'

services:
  # PostgreSQL service
  postgres:
    restart: always
    container_name: django-pgsql
    image: postgres:16-bullseye
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - magellans_site

  # Redis service
  redis:
    restart: always
    container_name: django-redis
    image: redis:5
    command: redis-server
    volumes:
      - redis_data:/data
    networks:
      - magellans_site


  # Django service
  django:
    restart: always
    container_name: django-app
    build:
      context: ./app
    command: ${COMMAND}
    volumes:
      - ./app:/app
    depends_on:
      - postgres
      - redis
    networks:
      - magellans_site


  # Nginx service
  nginx:
    restart: always
    container_name: django-nginx
    image: nginx:latest
    volumes:
      - ./nginx/${NGINX_CONF_FILE}:/etc/nginx/conf.d/default.conf
      - ${STATICFILES_DIR}:/app/staticfiles/
      - ${SSL_CERTS_DIR}:/app/ssl/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    networks:
      - magellans_site

postfix:
    image: catatnight/postfix
    container_name: postfix-mail-server
    hostname: mail-server
    restart: always
    environment:
      - MAIL_DOMAIN=magellans.fr
      - ALLOWED_SENDER_DOMAINS=magellans.fr
      - ALLOWED_NETWORKS=0.0.0.0/0
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - ./postfix/config:/etc/postfix
      - ./postfix/spool:/var/spool/postfix
      - ${SSL_CERTS_DIR}:/etc/postfix/ssl
      
dovecot:
  image: catatnight/dovecot
  container_name: dovecot-mail-server
  hostname: mail-server
  restart: always
  ports:
    - "143:143"
    - "993:993"
  volumes:
    - ./dovecot:/etc/dovecot
    - ./dovecot/mail:/var/mail
      - ${SSL_CERTS_DIR}:/etc/dovecot/ssl


volumes:
  postgres_data:
  redis_data: