version: '3.8'

networks:
  magellans_site:
    driver: 'bridge'

services:
  # PostgreSQL service
  postgres-django:
    restart: always
    stop_grace_period: 15s
    container_name: magellans-django-pgsql
    image: postgres:16-bullseye
    environment:
      POSTGRES_DB: ${DB_DJANGO_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data_django:/var/lib/postgresql/data
    networks:
      - magellans_site

  # Redis service
  redis:
    restart: always
    stop_grace_period: 15s
    container_name: magellans-redis
    image: redis:5
    command: ["redis-server"]
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - magellans_site

  # Django service
  django:
    restart: always
    stop_grace_period: 15s
    container_name: magellans-django
    build:
      context: ./app
    command: ${COMMAND}
    volumes:
      - ./app:/app
    depends_on:
      - postgres-django
      - redis
    networks:
      - magellans_site

  # Nginx service
  nginx:
    restart: always
    stop_grace_period: 15s
    container_name: magellans-nginx
    image: nginx:latest
    volumes:
      - ./nginx/${NGINX_CONF_FILE}:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${STATICFILES_DIR}:/app/staticfiles/
      - ${SSL_LETSENCRYPT}:${SSL_LETSENCRYPT}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    networks:
      - magellans_site

volumes:
  postgres_data_django:
  redis_data: