# Generated by Django 6.1.2 on 2026-10-06 20:14

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'Objet'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_created'], 'verbose_name': 'Réservation'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie'},
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Ajouté le'),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name="Description / conseils d'utilisation"),
        ),
        migrations.AddField(
            model_name='item',
            name='is_archived',
            field=models.BooleanField(default=False, help_text="Un objet archivé n'apparaît plus dans le catalogue.", verbose_name='Archivé'),
        ),
        migrations.AddField(
            model_name='order',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Matériel rendu le'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modifiée le'),
        ),
        migrations.AlterField(
            model_name='item',
            name='availability',
            field=models.IntegerField(choices=[(1, 'Réservable'), (2, 'Réservable (actuellement sorti)'), (0, 'Non réservable')], default=1, verbose_name='Réservation'),
        ),
        migrations.AlterField(
            model_name='item',
            name='buy_price',
            field=models.FloatField(blank=True, null=True, verbose_name="Prix d'achat (€)"),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='img/items/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='max_stock',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantité totale'),
        ),
        migrations.AlterField(
            model_name='item',
            name='now_available',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Disponible(s) (ancien site)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.IntegerField(choices=[(5, 'Neuf'), (4, 'Très bon état'), (3, 'Bon état'), (2, 'État moyen'), (1, 'Mauvais état'), (0, 'En maintenance'), (-1, 'Hors service')], default=4, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='warehouse.tag', verbose_name='Catégories'),
        ),
        migrations.AlterField(
            model_name='order',
            name='answer_message',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Réponses (ancien site)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Demande envoyée le'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_validated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Réponse donnée le'),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message du demandeur'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes internes du magasin'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_first_name',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Prénom de la personne qui récupère'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_last_name',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Nom de la personne qui récupère'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_phone',
            field=models.TextField(blank=True, default='', max_length=12, verbose_name='Téléphone de la personne qui récupère'),
        ),
        migrations.AlterField(
            model_name='order',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantities',
            field=models.TextField(default='{}', editable=False, verbose_name='Quantités (ancien site)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sent_by_mail',
            field=models.BooleanField(default=False, verbose_name='Notification envoyée'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Brouillon'), (1, 'En attente de réponse'), (2, 'Refusée'), (3, 'Acceptée — contrat à signer'), (4, 'Acceptée avec modifications — contrat à signer'), (5, 'Contrat signé'), (6, 'Terminée (matériel rendu)'), (7, 'Annulée')], default=0, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tos',
            field=models.BooleanField(default=True, verbose_name='Conditions acceptées'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#f5a524', max_length=10, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nom'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=200, verbose_name='Réalisateur·ice')),
                ('director_phone', models.CharField(max_length=30, verbose_name='Téléphone du / de la réalisateur·ice')),
                ('director_email', models.EmailField(max_length=254, verbose_name='E-mail du / de la réalisateur·ice')),
                ('production_name', models.CharField(max_length=200, verbose_name='Production')),
                ('production_address', models.CharField(blank=True, max_length=300, verbose_name='Adresse de la production')),
                ('production_phone', models.CharField(max_length=30, verbose_name='Téléphone de la production')),
                ('production_email', models.EmailField(max_length=254, verbose_name='E-mail de la production')),
                ('terms', models.JSONField(blank=True, default=dict, verbose_name='Conditions au moment de la signature')),
                ('signer_name', models.CharField(blank=True, max_length=200, verbose_name='Signé par')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Signé le')),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP du signataire')),
                ('signer_user_agent', models.CharField(blank=True, max_length=400, verbose_name='Navigateur du signataire')),
                ('signature_image', models.ImageField(blank=True, storage=core.storage.private_storage, upload_to=core.storage.UploadTo('contracts/signatures'), verbose_name='Signature')),
                ('pdf', models.FileField(blank=True, storage=core.storage.private_storage, upload_to=core.storage.UploadTo('contracts'), verbose_name='Contrat signé (PDF)')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='Empreinte SHA-256 du PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='warehouse.order', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Contrat de prêt',
                'verbose_name_plural': 'Contrats de prêt',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Quantité')),
                ('available', models.BooleanField(default=True, help_text='Décoché si le magasin ne peut pas prêter cet objet.', verbose_name='Accordé')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='warehouse.item', verbose_name='Objet')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.order', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Ligne de réservation',
                'verbose_name_plural': 'Lignes de réservation',
                'ordering': ['item__name'],
                'constraints': [models.UniqueConstraint(fields=('order', 'item'), name='unique_item_per_order')],
            },
        ),
    ]
