# Generated by Django 4.2.5 on 2023-10-08 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='ID Opération')),
                ('desc', models.TextField(verbose_name='Description')),
                ('direction', models.CharField(choices=[('C', 'Crédit'), ('D', 'Débit'), ('R', 'Remboursement')], max_length=1, verbose_name="Type d'opération")),
                ('amout', models.FloatField(verbose_name='Montant')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('status', models.CharField(choices=[('R', 'Reçue'), ('P', 'Prévisionnelle'), ('F', 'A faire'), ('J', 'En attente justificatif'), ('V', 'En attente de validation CA'), ('D', 'Demande des identifiants'), ('C', 'Virement en cours')], max_length=1, verbose_name='Statut')),
                ('dest', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination_operation', to=settings.AUTH_USER_MODEL, verbose_name="Receveur de l'opération")),
                ('src', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_operation', to=settings.AUTH_USER_MODEL, verbose_name="Emetteur de l'opération")),
            ],
        ),
    ]
