# Generated by Django 4.2.5 on 2023-10-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'Opération'},
        ),
        migrations.AlterField(
            model_name='operation',
            name='id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='ID Opération'),
        ),
    ]
