# Generated by Django 4.2.5 on 2023-10-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_operation_options_alter_operation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='direction',
            field=models.CharField(choices=[('C', 'Crédit'), ('D', 'Débit'), ('R', 'Remboursement')], default='D', max_length=1, verbose_name="Type d'opération"),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('R', 'Reçue'), ('P', 'Prévisionnelle'), ('F', 'A faire'), ('J', 'En attente justificatif'), ('V', 'En attente de validation CA'), ('D', 'Demande des identifiants'), ('C', 'Virement en cours')], default='J', max_length=1, verbose_name='Statut'),
        ),
    ]
