# Generated by Django 2.2.9 on 2023-11-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Courriel')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='CA')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('donation', models.FloatField(default=0, verbose_name='Montant donation')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='N° téléphone')),
                ('account', models.FloatField(default=0, verbose_name='Statut compte')),
                ('role', models.CharField(choices=[('P', 'Président.e'), ('C', 'Communication'), ('T', 'Trésorier.ère'), ('S', 'Secrétaire'), ('M', 'Membre'), ('E', 'Externe'), ('O', 'Organisation')], default='M', max_length=1, verbose_name='Role')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre')], max_length=1, verbose_name='Sexe')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
            },
        ),
    ]
