# Generated by Django 6.1.2 on 2026-10-06 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Compte', 'verbose_name_plural': 'Comptes'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name', 'pk'], 'verbose_name': 'Personne'},
        ),
        migrations.AlterModelOptions(
            name='unregisteredmember',
            options={'verbose_name': 'Externe site (ancien)', 'verbose_name_plural': 'Externes site (ancien)'},
        ),
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, max_length=800, verbose_name='Présentation'),
        ),
        migrations.AddField(
            model_name='person',
            name='board_roles',
            field=models.JSONField(blank=True, default=list, help_text='Codes des rôles CA (une personne peut en cumuler plusieurs).', verbose_name="Rôles au conseil d'administration"),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Créée le'),
        ),
        migrations.AddField(
            model_name='person',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='person',
            name='kind',
            field=models.CharField(choices=[('individual', 'Personne'), ('organisation', 'Organisation')], default='individual', max_length=12, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='person',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=200, verbose_name="Nom de l'organisation"),
        ),
        migrations.AddField(
            model_name='person',
            name='portfolio_url',
            field=models.URLField(blank=True, verbose_name='Portfolio / site'),
        ),
        migrations.AddField(
            model_name='person',
            name='show_in_directory',
            field=models.BooleanField(default=False, help_text='Visible uniquement par les adhérent·es connecté·es.', verbose_name="Apparaître dans l'annuaire des membres"),
        ),
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.JSONField(blank=True, default=list, verbose_name='Compétences'),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modifiée le'),
        ),
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.FloatField(default=0, verbose_name='Statut compte (ancien site)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='donation',
            field=models.FloatField(default=0, verbose_name='Montant donation (ancien site)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='additional_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes internes'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ext_profile',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ext_person', to='members.unregisteredmember', verbose_name='Profil externe lié (ancien)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme'), ('B', 'Non-binaire'), ('O', 'Autre')], max_length=1, null=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('P', 'Président.e'), ('C', 'Communication'), ('G', 'Gestionnaire magasin'), ('T', 'Trésorier.ère'), ('S', 'Secrétaire'), ('M', 'Membre Magellans & site'), ('Mx', 'Membre Magellans & pas site'), ('E', 'Inscrit site'), ('O', 'Organisation'), ('X', 'Externe site'), ('W', 'Webmaster')], default='X', help_text='Champ historique, remplacé par les rôles CA et les adhésions.', max_length=2, verbose_name='Rôle (ancien site)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='site_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_person', to=settings.AUTH_USER_MODEL, verbose_name='Compte du site'),
        ),
    ]
