# Generated by Django 4.2.5 on 2023-10-04 17:58

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_section_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=markdownx.models.MarkdownxField(null=True),
        ),
    ]
