# Generated by Django 6.1.2 on 2026-10-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification (ancien site)', 'verbose_name_plural': 'Notifications (ancien site)'},
        ),
    ]
