# Generated by Django 4.2.5 on 2023-10-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('P', 'Président.e'), ('C', 'Communication'), ('T', 'Trésorier'), ('S', 'Secrétaire'), ('M', 'Membre')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='donation',
            field=models.FloatField(default=0),
        ),
    ]
