# Generated by Django 4.2.5 on 2023-10-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_gender_member_role_alter_member_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.FloatField(default=0, verbose_name='Statut compte'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='member',
            name='donation',
            field=models.FloatField(default=0, verbose_name='Montant donation'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Courriel'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre')], max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='CA'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.IntegerField(verbose_name='ID Membre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='N° téléphone'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('P', 'Président.e'), ('C', 'Communication'), ('T', 'Trésorier.ère'), ('S', 'Secrétaire'), ('M', 'Membre')], default='M', max_length=1, verbose_name='Role'),
        ),
    ]
