# Generated by Django 4.2.5 on 2023-10-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_account_alter_member_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Membre', 'verbose_name_plural': 'Membres'},
        ),
    ]
