# Generated by Django 4.2.5 on 2023-10-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('P', 'Président.e'), ('C', 'Communication'), ('T', 'Trésorier.ère'), ('S', 'Secrétaire'), ('M', 'Membre'), ('E', 'Externe'), ('O', 'Organisation')], default='M', max_length=1, verbose_name='Role'),
        ),
    ]
