# Generated by Django 6.1.2 on 2026-10-06 20:14

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
        ('members', '0002_refonte_2026'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-release_date', 'name'], 'verbose_name': 'Projet'},
        ),
        migrations.AlterModelOptions(
            name='projectfundingrequest',
            options={'ordering': ['-deposit_date'], 'verbose_name': "Demande d'aide à projet", 'verbose_name_plural': "Demandes d'aide à projet"},
        ),
        migrations.AlterModelOptions(
            name='resourcefile',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Ressource'},
        ),
        migrations.AlterModelOptions(
            name='rolemap',
            options={'ordering': ['order', 'role_name', 'pk'], 'verbose_name': 'Poste au générique', 'verbose_name_plural': 'Générique'},
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='project',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Durée (minutes)'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, verbose_name="Mis en avant sur l'accueil"),
        ),
        migrations.AddField(
            model_name='project',
            name='festivals',
            field=models.TextField(blank=True, help_text='Un par ligne.', verbose_name='Festivals & distinctions'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('development', 'En développement'), ('preproduction', 'En préparation'), ('shooting', 'En tournage'), ('postproduction', 'En post-production'), ('released', 'Sorti')], max_length=20, verbose_name='Avancement'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Film ou bande-annonce (YouTube / Vimeo)'),
        ),
        migrations.AddField(
            model_name='projectfundingrequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Décision prise le'),
        ),
        migrations.AddField(
            model_name='projectfundingrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Décision saisie par'),
        ),
        migrations.AddField(
            model_name='projectfundingrequest',
            name='decision_note',
            field=models.TextField(blank=True, verbose_name='Réponse du CA'),
        ),
        migrations.AddField(
            model_name='projectfundingrequest',
            name='granted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Montant accordé (€)'),
        ),
        migrations.AddField(
            model_name='projectfundingrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Déposée'), ('reviewing', "En cours d'examen"), ('accepted', 'Acceptée'), ('partial', 'Acceptée partiellement'), ('refused', 'Refusée'), ('withdrawn', 'Retirée')], default='submitted', max_length=12, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='resourcefile',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Ajoutée le'),
        ),
        migrations.AddField(
            model_name='resourcefile',
            name='external_url',
            field=models.URLField(blank=True, help_text="À la place d'un fichier (Drive, Notion…).", verbose_name='Lien externe'),
        ),
        migrations.AddField(
            model_name='rolemap',
            name='label',
            field=models.CharField(blank=True, help_text='Ex. « Rôle de Mia ».', max_length=120, verbose_name='Intitulé personnalisé'),
        ),
        migrations.AddField(
            model_name='rolemap',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(verbose_name='Synopsis / présentation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_projects', to='members.person', verbose_name='Réalisateur·ice'),
        ),
        migrations.AlterField(
            model_name='project',
            name='money_handler',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_projects', to='members.person', verbose_name='Responsable financier·ère'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='project',
            name='poster',
            field=models.ImageField(blank=True, default='', upload_to='img/projects/', verbose_name='Affiche'),
        ),
        migrations.AlterField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Visible dans le catalogue public'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Accroche'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='projectfundingrequest',
            name='asker',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_requests', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur·se'),
        ),
        migrations.AlterField(
            model_name='projectfundingrequest',
            name='contact_list',
            field=models.FileField(storage=core.storage.private_storage, upload_to=core.storage.UploadTo('funding_requests'), verbose_name='Fiche contact'),
        ),
        migrations.AlterField(
            model_name='projectfundingrequest',
            name='deposit_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Déposée le'),
        ),
        migrations.AlterField(
            model_name='projectfundingrequest',
            name='directors',
            field=models.CharField(max_length=255, verbose_name='Réalisateur·ices'),
        ),
        migrations.AlterField(
            model_name='projectfundingrequest',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Durée estimée (minutes)'),
        ),
        migrations.AlterField(
            model_name='projectfundingrequest',
            name='explanation',
            field=models.TextField(verbose_name='Pourquoi cette demande ?'),
        ),
        migrations.AlterField(
            model_name='projectfundingrequest',
            name='funding_value',
            field=models.PositiveIntegerField(verbose_name='Montant demandé (€)'),
        ),
        migrations.AlterField(
            model_name='projectfundingrequest',
            name='intention_note',
            field=models.FileField(storage=core.storage.private_storage, upload_to=core.storage.UploadTo('funding_requests'), verbose_name="Note d'intention"),
        ),
        migrations.AlterField(
            model_name='projectfundingrequest',
            name='previsional_budget_plan',
            field=models.FileField(storage=core.storage.private_storage, upload_to=core.storage.UploadTo('funding_requests'), verbose_name='Plan de financement prévisionnel'),
        ),
        migrations.AlterField(
            model_name='projectfundingrequest',
            name='previsional_shoot_end_date',
            field=models.DateField(verbose_name='Fin prévisionnelle du tournage'),
        ),
        migrations.AlterField(
            model_name='projectfundingrequest',
            name='previsional_shoot_start_date',
            field=models.DateField(verbose_name='Début prévisionnel du tournage'),
        ),
        migrations.AlterField(
            model_name='projectfundingrequest',
            name='role',
            field=models.CharField(max_length=255, verbose_name='Ton poste sur le projet'),
        ),
        migrations.AlterField(
            model_name='projectfundingrequest',
            name='script',
            field=models.FileField(storage=core.storage.private_storage, upload_to=core.storage.UploadTo('funding_requests'), verbose_name='Scénario'),
        ),
        migrations.AlterField(
            model_name='projectfundingrequest',
            name='sent_by_mail',
            field=models.BooleanField(default=False, verbose_name='Dossier envoyé par e-mail'),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='associated_file',
            field=models.FileField(blank=True, storage=core.storage.private_storage, upload_to=core.storage.UploadTo('resources'), verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rolemap',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='members.person', verbose_name='Personne'),
        ),
        migrations.AlterField(
            model_name='rolemap',
            name='role_name',
            field=models.IntegerField(choices=[(1, 'Réalisation'), (2, 'Production'), (3, 'Scénario'), (4, 'Direction de la photographie'), (5, 'Montage'), (6, 'Son / design sonore'), (7, 'Décors'), (8, 'Costumes'), (9, 'Maquillage'), (10, 'Interprétation'), (11, 'Assistanat réalisation'), (12, 'Assistanat production'), (13, 'Lumière'), (14, 'Machinerie'), (15, 'Perche'), (16, 'Musique'), (17, 'Effets visuels'), (18, 'Cascades'), (19, 'Casting'), (99, 'Autre')], verbose_name='Poste'),
        ),
    ]
